# Generated by Django 4.2.1 on 2026-03-18 19:09

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0002_alter_booking_currency_alter_booking_paid_amount_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bookingtraveler',
            name='age',
            field=models.PositiveSmallIntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(110)]),
        ),
    ]
