# Generated by Django 4.2.1 on 2026-03-30 12:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0003_alter_bookingtraveler_age'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bookingpayment',
            name='payment_method',
            field=models.CharField(choices=[('card', 'Card'), ('bank_transfer', 'Bank Transfer'), ('wallet', 'Wallet'), ('cash', 'Cash'), ('esewa', 'eSewa'), ('khalti', 'Khalti'), ('other', 'Other')], max_length=20),
        ),
    ]
