LANGUAGE_ENGLISH = "en"
LANGUAGE_NEPALI = "ne"

LANGUAGE_CHOICES = (
    (LANGUAGE_ENGLISH, "English"),
    (LANGUAGE_NEPALI, "Nepali"),
)

APPEARANCE_LIGHT = "light"
APPEARANCE_DARK = "dark"

APPEARANCE_CHOICES = (
    (APPEARANCE_LIGHT, "Light"),
    (APPEARANCE_DARK, "Dark"),
)

CURRENCY_NPR = "NPR"
CURRENCY_USD = "USD"

CURRENCY_CHOICES = (
    (CURRENCY_NPR, "Nepalese Rupee"),
    (CURRENCY_USD, "US Dollar"),
)

DEFAULT_LANGUAGE = LANGUAGE_ENGLISH
DEFAULT_APPEARANCE = APPEARANCE_LIGHT
DEFAULT_CURRENCY = CURRENCY_NPR