# Generated by Django 4.2.1 on 2026-03-18 19:16

from decimal import Decimal
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0002_alter_contentcategory_created_by_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='story',
            name='read_time_minutes',
            field=models.PositiveSmallIntegerField(default=5, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(300)]),
        ),
        migrations.AlterField(
            model_name='testimonial',
            name='rating',
            field=models.DecimalField(decimal_places=1, default=5.0, max_digits=3, validators=[django.core.validators.MinValueValidator(Decimal('0.0')), django.core.validators.MaxValueValidator(Decimal('5.0'))]),
        ),
    ]
