# Generated by Django 4.2.1 on 2026-03-18 16:18

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='guideprofile',
            options={'ordering': ['-created_at']},
        ),
        migrations.AlterModelOptions(
            name='notification',
            options={'ordering': ['-created_at']},
        ),
        migrations.AlterModelOptions(
            name='user',
            options={'ordering': ['-created_at']},
        ),
        migrations.AlterModelOptions(
            name='userprofile',
            options={'ordering': ['-created_at']},
        ),
        migrations.AlterModelOptions(
            name='wishlist',
            options={'ordering': ['-created_at']},
        ),
        migrations.RemoveField(
            model_name='wishlist',
            name='added_at',
        ),
        migrations.AlterField(
            model_name='guideprofile',
            name='address_proof',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='guideprofile',
            name='available_regions',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AlterField(
            model_name='guideprofile',
            name='certifications',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AlterField(
            model_name='guideprofile',
            name='custom_rates',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AlterField(
            model_name='guideprofile',
            name='gallery_images',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AlterField(
            model_name='guideprofile',
            name='id_proof',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='guideprofile',
            name='languages_certified',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AlterField(
            model_name='guideprofile',
            name='languages_spoken',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AlterField(
            model_name='guideprofile',
            name='license_document',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='guideprofile',
            name='police_clearance',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='guideprofile',
            name='profile_photo',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='guideprofile',
            name='region_expertise',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AlterField(
            model_name='guideprofile',
            name='review_tags',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AlterField(
            model_name='guideprofile',
            name='specializations',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AlterField(
            model_name='guideprofile',
            name='unavailable_dates',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AlterField(
            model_name='notification',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='userotp',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='otp_codes', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='wishlist',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='wishlists', to=settings.AUTH_USER_MODEL),
        ),
    ]
