# Generated by Django 4.2.1 on 2026-03-23 05:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_userpreference'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='userpreference',
            options={},
        ),
        migrations.AlterModelTable(
            name='userpreference',
            table=None,
        ),
    ]
