# Generated by Django 4.2.1 on 2026-03-18 17:46

from decimal import Decimal
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('flights', '0002_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='airline',
            options={'ordering': ['name']},
        ),
        migrations.AlterModelOptions(
            name='airport',
            options={'ordering': ['country', 'city', 'name']},
        ),
        migrations.AlterModelOptions(
            name='flight',
            options={'ordering': ['departure_time', 'flight_number']},
        ),
        migrations.AlterModelOptions(
            name='flightroute',
            options={'ordering': ['origin__city', 'destination__city']},
        ),
        migrations.AlterModelOptions(
            name='flightsearch',
            options={'ordering': ['-created_at']},
        ),
        migrations.AlterField(
            model_name='airport',
            name='country',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='flight',
            name='base_price',
            field=models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))]),
        ),
        migrations.AlterField(
            model_name='flight',
            name='currency',
            field=models.CharField(default='USD', max_length=3),
        ),
        migrations.AlterField(
            model_name='flightroute',
            name='destination',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='routes_to', to='flights.airport'),
        ),
    ]
