name: Django CI (Docker)

on:
  push:
    branches:
      - master  

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Debug files
        run: ls -R

      - name: Create .env file
        run: |
          echo "SECRET_KEY=${{ secrets.DJANGO_SECRET_KEY }}" >> bolttrip/.env
          echo "DEBUG=1" >> bolttrip/.env
          echo "DB_NAME=${{ secrets.DB_NAME }}" >> bolttrip/.env
          echo "DB_USER=${{ secrets.DB_USER }}" >> bolttrip/.env
          echo "DB_PASSWORD=${{ secrets.DB_PASSWORD }}" >> bolttrip/.env
          echo "DB_HOST=db" >> bolttrip/.env
          echo "DB_PORT=5432" >> bolttrip/.env

      - name: Build containers
        working-directory: bolttrip
        run: docker compose build

      - name: Start containers
        working-directory: bolttrip
        run: docker compose up -d

      - name: Show running containers
        working-directory: bolttrip
        run: docker compose ps

      - name: Show logs (IMPORTANT)
        working-directory: bolttrip
        run: docker compose logs

      - name: Wait for containers
        run: sleep 15
        
      - name: Run migrations
        working-directory: bolttrip
        run: docker compose exec -T web python manage.py migrate --noinput

      - name: Run tests
        working-directory: bolttrip
        run: docker compose exec -T web python manage.py test

      - name: Stop containers
        if: always()
        working-directory: bolttrip
        run: docker compose down
